name: Publish Release

on:
  push:
    branches: ["main"]
    tags:
      - "v*"

jobs:
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64

      - name: Setup Gradle and publish build scans
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Display environment info
        run: |
          ./gradlew -v
          uname -a

      - name: Test using gradle
        run: |
          ./gradlew test -q -S

      - name: Remove Gradle cache lock file
        if: always()
        run: rm -rvf $HOME/.gradle/caches/modules-2/modules-2.lock

      - name: Full Coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          codecov_yml_path: ./codecov.yml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: VenomVendor/NullDefense
          file: ./build/reports/jacoco/report.xml

  publish:
    name: Publish artifacts
    runs-on: ubuntu-latest
    environment: publish
    needs: code-coverage
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64

      - name: Setup Gradle and publish build scans
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Display environment info
        run: |
          ./gradlew -v
          uname -a

      - name: Build using gradle
        run: |
          echo "Publishing triggered from ${GITHUB_REF_NAME}"
          ./gradlew publish --no-configuration-cache -q -S

      - name: Remove Gradle cache lock file
        if: always()
        run: rm -rvf $HOME/.gradle/caches/modules-2/modules-2.lock
