name: Publish Artifacts

on:
  push:
    branches: ["main"]
    tags:
      - "v*"

jobs:
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64

      - name: Setup Gradle and publish build scans
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Display environment info
        run: |
          ./gradlew -v
          uname -a

      - name: Test using gradle
        run: |
          ./gradlew test -q -S

      - name: Remove Gradle cache lock file
        if: always()
        run: rm -rvf $HOME/.gradle/caches/modules-2/modules-2.lock

      - name: Full Coverage | Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          codecov_yml_path: ./codecov.yml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: VenomVendor/NullDefense
          file: build/reports/jacoco/report.xml

      - name: Full Coverage | Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/reports/jacoco/report.xml

      - name: Full Coverage | Codeclimate
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_PROJECT_TOKEN }}
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageLocations: build/reports/jacoco/report.xml:jacoco

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/reports/
          retention-days: 1
          compression-level: 9

  publish:
    name: Ship it!
    runs-on: ubuntu-latest
    environment: publish
    needs: code-coverage
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64

      - name: Setup Gradle and publish build scans
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Display environment info
        run: |
          ./gradlew -v
          uname -a

      - name: Build using gradle
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          echo "Publishing triggered from ${GITHUB_REF_NAME}"
          ./gradlew publish --no-configuration-cache -q -S

      - name: Remove Gradle cache lock file
        if: always()
        run: rm -rvf $HOME/.gradle/caches/modules-2/modules-2.lock

      - name: Attest
        uses: actions/attest-build-provenance@v1.3.3
        with:
          subject-path: "build/libs/**/*"
